import { resolve, relative } from 'path';
import { readFileSync, existsSync } from 'fs';
import matter from 'gray-matter';
import { loadUserConfig, resolveConfig, resolveSections } from '../core/config.js';
import { scanDocs, type DocFile } from '../core/navigation.js';
import type { DocCategory } from '../types/index.js';

interface BrokenLink {
  file: string;
  line: number;
  link: string;
  suggestion?: string;
}

export interface CheckOptions {
  frontmatterOnly?: boolean;
}

// ---------------------------------------------------------------------------
// Frontmatter validation
// ---------------------------------------------------------------------------

const VALID_CATEGORIES: DocCategory[] = [
  'documentation', 'internal', 'plan', 'research', 'decision', 'roadmap', 'changelog',
];
const VALID_STATUSES = ['active', 'superseded', 'archived'] as const;

interface FrontmatterIssue {
  file: string;
  field: string;
  message: string;
  severity: 'error' | 'warning';
}

/**
 * Determine whether a file path falls within docs/plans/ or docs/internal/
 * (stricter requirements) vs docs/public/ (looser).
 */
function isStrictPath(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, '/');
  return /\/docs\/plans(\/|$)/.test(normalized) ||
         /\/docs\/internal(\/|$)/.test(normalized);
}

function validateFrontmatter(doc: DocFile, userRoot: string): FrontmatterIssue[] {
  const issues: FrontmatterIssue[] = [];
  const rel = relative(userRoot, doc.filePath);
  const strict = isStrictPath(doc.filePath);

  // Read raw frontmatter from disk so we can distinguish "absent" from
  // "auto-generated by scanDocs" (which fills in a title from the filename).
  let rawFm: Record<string, unknown> = {};
  try {
    const content = readFileSync(doc.filePath, 'utf-8');
    rawFm = matter(content).data;
  } catch {
    rawFm = {};
  }

  // --- Required field checks ------------------------------------------------

  if (strict) {
    // docs/plans/ and docs/internal/ — title, summary, category are required (errors)
    if (!rawFm.title) {
      issues.push({ file: rel, field: 'title', message: 'missing required field', severity: 'error' });
    }
    if (!rawFm.summary) {
      issues.push({ file: rel, field: 'summary', message: 'missing required field', severity: 'error' });
    }
    if (!rawFm.category) {
      issues.push({ file: rel, field: 'category', message: 'missing required field', severity: 'error' });
    }
  } else {
    // docs/public/ (and everything else) — title required, rest recommended
    if (!rawFm.title) {
      issues.push({ file: rel, field: 'title', message: 'missing required field', severity: 'error' });
    }
    if (!rawFm.summary) {
      issues.push({ file: rel, field: 'summary', message: 'recommended field missing', severity: 'warning' });
    }
    if (!rawFm.category) {
      issues.push({ file: rel, field: 'category', message: 'recommended field missing', severity: 'warning' });
    }
  }

  // --- Value validation (applies everywhere when field is present) -----------

  if (rawFm.category !== undefined) {
    if (!VALID_CATEGORIES.includes(rawFm.category as DocCategory)) {
      issues.push({
        file: rel,
        field: 'category',
        message: `invalid value "${rawFm.category}" (allowed: ${VALID_CATEGORIES.join(', ')})`,
        severity: 'error',
      });
    }
  }

  if (rawFm.status !== undefined) {
    if (!(VALID_STATUSES as readonly string[]).includes(rawFm.status as string)) {
      issues.push({
        file: rel,
        field: 'status',
        message: `invalid value "${rawFm.status}" (allowed: ${VALID_STATUSES.join(', ')})`,
        severity: 'error',
      });
    }
  }

  if (rawFm.tags !== undefined && !Array.isArray(rawFm.tags)) {
    issues.push({ file: rel, field: 'tags', message: 'must be an array', severity: 'error' });
  }

  if (rawFm.projects !== undefined && !Array.isArray(rawFm.projects)) {
    issues.push({ file: rel, field: 'projects', message: 'must be an array', severity: 'error' });
  }

  return issues;
}

export async function checkFrontmatter(): Promise<{ errors: number; warnings: number }> {
  const userRoot = process.cwd();
  const userConfig = await loadUserConfig(userRoot);
  const config = resolveConfig(userConfig, userRoot);
  const sections = await resolveSections(config, userRoot);

  const allDocs: DocFile[] = [];
  for (const section of sections) {
    const docs = scanDocs(section.docsDir, section.exclude, section.basePath);
    allDocs.push(...docs);
  }

  const allIssues: FrontmatterIssue[] = [];
  for (const doc of allDocs) {
    const issues = validateFrontmatter(doc, userRoot);
    allIssues.push(...issues);
  }

  const errors = allIssues.filter((i) => i.severity === 'error');
  const warnings = allIssues.filter((i) => i.severity === 'warning');

  if (allIssues.length === 0) {
    console.log('\n  Frontmatter: all files valid.\n');
    return { errors: 0, warnings: 0 };
  }

  // Print table
  console.log(`\n  Frontmatter validation: ${errors.length} error(s), ${warnings.length} warning(s)\n`);

  // Calculate column widths
  const fileCol = Math.max(4, ...allIssues.map((i) => i.file.length));
  const fieldCol = Math.max(5, ...allIssues.map((i) => i.field.length));
  const msgCol = Math.max(7, ...allIssues.map((i) => i.message.length));
  const sevCol = 7; // "warning" is the longest

  const header = `  ${'File'.padEnd(fileCol)}  ${'Field'.padEnd(fieldCol)}  ${'Severity'.padEnd(sevCol)}  ${'Message'.padEnd(msgCol)}`;
  const separator = `  ${'─'.repeat(fileCol)}  ${'─'.repeat(fieldCol)}  ${'─'.repeat(sevCol)}  ${'─'.repeat(msgCol)}`;

  console.log(header);
  console.log(separator);

  for (const issue of allIssues) {
    const sev = issue.severity === 'error' ? 'ERROR  ' : 'warning';
    console.log(`  ${issue.file.padEnd(fileCol)}  ${issue.field.padEnd(fieldCol)}  ${sev}  ${issue.message}`);
  }
  console.log();

  return { errors: errors.length, warnings: warnings.length };
}

// ---------------------------------------------------------------------------
// Broken-link checking (existing functionality, unchanged)
// ---------------------------------------------------------------------------

export async function checkLinks(options: CheckOptions = {}): Promise<void> {
  // Run frontmatter checks first (or exclusively)
  const fmResult = await checkFrontmatter();

  if (options.frontmatterOnly) {
    if (fmResult.errors > 0) {
      process.exitCode = 1;
    }
    return;
  }

  // Continue with broken-link detection
  const userRoot = process.cwd();
  const userConfig = await loadUserConfig(userRoot);
  const config = resolveConfig(userConfig, userRoot);
  const sections = await resolveSections(config, userRoot);

  // Build the set of all valid routes
  const validRoutes = new Set<string>();
  const allDocs: { filePath: string; routePath: string }[] = [];

  for (const section of sections) {
    const docs = scanDocs(section.docsDir, section.exclude, section.basePath);
    for (const doc of docs) {
      validRoutes.add(doc.routePath);
      allDocs.push(doc);
    }
  }

  // Always add root, changelog, and roadmap
  validRoutes.add('/');
  const changelogPath = resolve(userRoot, 'CHANGELOG.md');
  if (existsSync(changelogPath)) {
    validRoutes.add('/changelog');
  }
  const roadmapPath = resolve(userRoot, 'ROADMAP.md');
  if (existsSync(roadmapPath)) {
    validRoutes.add('/roadmap');
  }

  // Also add routes without trailing slash and with trailing slash
  const expandedRoutes = new Set(validRoutes);
  for (const route of validRoutes) {
    expandedRoutes.add(route.replace(/\/$/, ''));
    if (route !== '/') expandedRoutes.add(route + '/');
  }

  // Regex patterns for links in markdown/MDX
  // Markdown links: [text](path) or [text](path "title")
  const mdLinkRegex = /\[(?:[^\]]*)\]\(([^)]+)\)/g;
  // HTML href: href="path" or href='path'
  const hrefRegex = /href=["']([^"']+)["']/g;

  const brokenLinks: BrokenLink[] = [];

  for (const doc of allDocs) {
    if (!existsSync(doc.filePath)) continue;
    const content = readFileSync(doc.filePath, 'utf-8');
    const lines = content.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const lineNum = i + 1;

      // Skip code blocks
      if (line.trimStart().startsWith('```')) continue;

      for (const regex of [mdLinkRegex, hrefRegex]) {
        regex.lastIndex = 0;
        let match;
        while ((match = regex.exec(line)) !== null) {
          const rawLink = match[1].split(/[\s"'#]/)[0]; // Strip title, hash, quotes

          // Skip external links, anchors, mailto, tel, protocol links
          if (!rawLink || rawLink.startsWith('http://') || rawLink.startsWith('https://') ||
              rawLink.startsWith('#') || rawLink.startsWith('mailto:') ||
              rawLink.startsWith('tel:') || rawLink.startsWith('//') ||
              rawLink.startsWith('{') || rawLink.startsWith('data:')) {
            continue;
          }

          // Skip relative file links to assets (images, etc.)
          if (/\.(png|jpe?g|gif|svg|webp|ico|pdf|zip|tar|gz)$/i.test(rawLink)) {
            continue;
          }

          // Normalize the link path
          let normalized = rawLink;
          // Remove .md/.mdx extension if present
          normalized = normalized.replace(/\.(mdx?|html?)$/, '');
          // Ensure leading slash
          if (!normalized.startsWith('/')) {
            // Resolve relative to current doc's directory
            const docDir = doc.routePath.substring(0, doc.routePath.lastIndexOf('/')) || '/';
            normalized = docDir === '/' ? '/' + normalized : docDir + '/' + normalized;
          }
          // Remove trailing slash for comparison (except root)
          const check = normalized === '/' ? '/' : normalized.replace(/\/$/, '');

          // Remove /index suffix
          const checkNoIndex = check.replace(/\/index$/, '') || '/';

          if (!expandedRoutes.has(check) && !expandedRoutes.has(checkNoIndex)) {
            // Find closest match for suggestion
            const suggestion = findClosest(check, validRoutes);
            brokenLinks.push({
              file: doc.filePath,
              line: lineNum,
              link: rawLink,
              ...(suggestion ? { suggestion } : {}),
            });
          }
        }
      }
    }
  }

  // Report results
  if (brokenLinks.length === 0) {
    console.log('\n  No broken links found.\n');
  } else {
    console.log(`\n  Found ${brokenLinks.length} broken link${brokenLinks.length === 1 ? '' : 's'}:\n`);

    // Group by file
    const byFile = new Map<string, BrokenLink[]>();
    for (const bl of brokenLinks) {
      const rel = bl.file.replace(userRoot + '/', '');
      if (!byFile.has(rel)) byFile.set(rel, []);
      byFile.get(rel)!.push(bl);
    }

    for (const [file, links] of byFile) {
      console.log(`  ${file}`);
      for (const link of links) {
        const suggestion = link.suggestion ? ` (did you mean ${link.suggestion}?)` : '';
        console.log(`    line ${link.line}: ${link.link}${suggestion}`);
      }
      console.log();
    }
  }

  // Exit with code 1 if any errors found (broken links or frontmatter errors)
  if (brokenLinks.length > 0 || fmResult.errors > 0) {
    process.exitCode = 1;
  }
}

function findClosest(target: string, routes: Set<string>): string | undefined {
  let best: string | undefined;
  let bestScore = Infinity;

  const targetSegments = target.split('/').filter(Boolean);

  for (const route of routes) {
    const routeSegments = route.split('/').filter(Boolean);

    // Simple scoring: Levenshtein on the full path string
    const dist = levenshtein(target, route);
    // Bonus for shared segments
    const common = targetSegments.filter((s) => routeSegments.includes(s)).length;
    const score = dist - common * 2;

    if (score < bestScore) {
      bestScore = score;
      best = route;
    }
  }

  // Only suggest if reasonably close
  if (best && bestScore < target.length * 0.6) return best;
  return undefined;
}

function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  const dp: number[][] = Array.from({ length: m + 1 }, () => Array(n + 1).fill(0));
  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] = a[i - 1] === b[j - 1]
        ? dp[i - 1][j - 1]
        : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
    }
  }
  return dp[m][n];
}
